### ISSUE TITLE
Running this playbook

### ISSUE THREAD

**Issue by alexseys** [ColOfAbRiX/role-tripwire#1]
Hi
Have cloned and ran your playbook against a host (only one host is in the list)   i.e.:

ansible-playbook -i /path/ansible-hosts -s /path/hosts.yaml --limit tripwire_servers -vvv
Result:
[DEPRECATION WARNING]: The sudo command line option has been deprecated in favor of the "become" command line arguments. This feature will
be removed in version 2.6. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [tripwire_servers] *********************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************
ok: [HOST]

PLAY RECAP **********************************************************************************************************************************
HOST    : ok=1    changed=0    unreachable=0    failed=0

Seems like it finished OK, but nothing is installed on the server

Wandering if you can give some pointers where to go from here?

Thank you.

**Comment by ColOfAbRiX** [comment]
It looks something is missing. Right now I can't understand if the host or the tasks.
Can I see your playbook file and inventory?
